### ISSUE TITLE
minor comments on ess_imse

### ISSUE THREAD

**Issue by magland** [flatironinstitute/bayes-kit#12]
https://github.com/flatironinstitute/bayes-kit/blob/8f8c494cf65ce39f0982566b54ed1a9a277f8c82/bayes_kit/ess.py#L99-L135

I have a couple comments about this function. These are minor so feel free to ignore!

First, I think isotonic regression is a better choice than this scheme for approximating the decay by a monotonically decreasing sequence. This scheme will tend to underestimate the area under the curve. Take the following example: `1, 0.3, 0.6, 0`

(Ignoring the pairing part of this) The present scheme would approximate it by `1, 0.3, 0.3, 0`, whereas isotonic regression would give `1, 0.45, 0.45, 0`. The integral of the former is 1.6, whereas the later is 1.9.

My second comment is that when n is even, the n-1 sample of the acor is neglected.

**Comment by magland** [comment]
Looking more closely, I think I will rescind my suggestion for isotonic regression -- because in that case you get the same area under curve as the original - and I guess that's not what we want.

**Comment by bob-carpenter** [comment]
I think it's OK to neglect the `n - 1`-lag autocorrelation in a sequence of length `n`.  There's not enough data to estimate it anyway. 

I'm just going to close this, but if you think that's wrong, please re-open.
