### ISSUE TITLE
small bug in ess_imse

### ISSUE THREAD

**Issue by magland** [flatironinstitute/bayes-kit#13]
https://github.com/flatironinstitute/bayes-kit/blob/8f8c494cf65ce39f0982566b54ed1a9a277f8c82/bayes_kit/ess.py#L124-L130

I think minprev should really be prev_min

**Comment by bob-carpenter** [comment]
D'oh.  I need to keep updating `prev_min`. 

In case you're getting super worried about the shoddy code here, these functions hadn't gone through code review yet and haven't been thoroughly tested.  I probably shouldn't have given them to you as reference implementations.   That goes for the rest of the repo, too.

So I really appreciate the feedback at this stage.
