### ISSUE TITLE
in first_neg_pair_start, use n = n + 1

### ISSUE THREAD

**Issue by magland** [flatironinstitute/bayes-kit#15]
https://github.com/flatironinstitute/bayes-kit/blob/8f8c494cf65ce39f0982566b54ed1a9a277f8c82/bayes_kit/ess.py#L57-L75

I think line 74 should be `n = n + 1` instead of `n = n + 2` to be consistent with the description of the function. Also, with `n = n + 2` I confirmed that you can get negative contributions to the area under the ACF.

**Comment by magland** [comment]
Also, if this is changed to `n = n + 1` then there is the possibility that the return value is 1, in which case, you should modify the following code to not count the contribution from acor[1] + acor[2] (in the case where n=1):

https://github.com/flatironinstitute/bayes-kit/blob/8f8c494cf65ce39f0982566b54ed1a9a277f8c82/bayes_kit/ess.py#L123-L131

**Comment by bob-carpenter** [comment]
Thanks!  The algebra slipped by a -1 when I went to working by pairs.  Fixing now.
