### ISSUE TITLE
implement split R-hat a la BDA3

### ISSUE THREAD

**Issue by bob-carpenter** [flatironinstitute/bayes-kit#36]
Add an implementation of split R-hat as detailed in BDA3.

**Comment by jsoules** [comment]
That's [Bayesian Data Analysis, 3rd Edition](http://www.stat.columbia.edu/~gelman/book/)?

**Comment by bob-carpenter** [comment]
Yes.  I put the full citation in the code as a reference.  The spine of the physical book just says "BDA3," so that's what everyone calls it.

**Comment by bob-carpenter** [comment]
I'm also implementing the ranked r-hat as part of the same PR.
